// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// biome-ignore lint/correctness/noUnusedVariables: cf runtime
interface Env {
  ASSET: Fetcher;
}
